name: Docker Build

on:
  push:
    branches: [main]
    paths:
      - 'server/Dockerfile'
      - 'client/Dockerfile' 
      - 'docker-compose.yml'
      - 'server/**'
      - 'client/**'
  pull_request:
    branches: [main]
    paths:
      - 'server/Dockerfile'
      - 'client/Dockerfile'
      - 'docker-compose.yml'
  workflow_dispatch: 

jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create test environment files
        run: |
          echo "Creating test .env files for Docker validation..."
          echo "MongoDB_URI=mongodb://test:test@localhost:27017/test" > server/.env
          echo "AV_API=test_api_key" >> server/.env
          echo "UPSTASH_REDIS_REST_URL=https://test-redis.upstash.io" >> server/.env
          echo "UPSTASH_REDIS_REST_TOKEN=test_token" >> server/.env
          echo "NEXT_PUBLIC_API_URL=http://localhost:1000" > client/.env
      
      - name: Build server Docker image
        run: |
          echo "Building server image..."
          docker build -t tickr-server ./server
          
      - name: Build client Docker image  
        run: |
          echo "Building client image..."
          docker build -t tickr-client ./client
          
      - name: Test Docker Compose
        run: |
          echo "Testing Docker Compose configuration..."
          docker compose config
          docker compose build
          
      - name: Create issue on Docker failure
        if: failure()
        uses: actions-cool/issues-helper@v3
        with:
          actions: "create-issue"
          title: "🚨 Docker Build Failed - ${{ github.sha }}"
          body: |
            **Docker Build/Test Failed**
            
            - **Commit**: ${{ github.sha }}
            - **Branch**: ${{ github.ref_name }}
            - **Workflow**: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            
            **Possible Issues:**
            - Dockerfile syntax errors
            - Missing dependencies in containers
            - Docker Compose configuration issues
            - Build context problems
            - Base image issues
            
            @${{ github.actor }}