name: Scheduled stock fetch (AlphaVantage)
on:
  schedule:
    # Run daily at 21:00 UTC == 05:00 Asia/Manila (next day)
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: server
        run: npm ci

      - name: Run fetch script
        working-directory: server
        env:
          AV_API: ${{ secrets.AV_API }}
          MongoDB_URI: ${{ secrets.MongoDB_URI }}
          UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
          UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
        run: npx ts-node src/scripts/run-fetch.ts